import Link from 'next/link';
import { FullStory } from '@/components/full-story';
import { SavePlace } from '@/components/saved-places';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { findPlace } from '@/lib/places';
import { Header, Footer } from '@/components/site-shell';
type Props = { params: Promise<{slug:string}> };
export async function generateMetadata({params}:Props):Promise<Metadata> {
 const {slug}=await params;const p=findPlace(slug);if(!p)return {title:'Place not found'};
 return {title:`${p.name}, ${p.country}: Story & Visiting`,description:p.hook,alternates:{canonical:`/places/${p.slug}`}};
}
export default async function PlacePage({params}:Props) {
 const {slug}=await params;const p=findPlace(slug);if(!p)notFound();
 const structured={ '@context':'https://schema.org','@type':'Article',headline:`${p.name}: ${p.storyTitle}`,description:p.hook,dateModified:'2026-10-08',author:{'@type':'Organization',name:'Odd Atlas'},mainEntityOfPage:`https://odd-atlas.dwitimehta20.chatgpt.site/places/${p.slug}`,about:{'@type':'Place',name:p.name,address:{'@type':'PostalAddress',addressRegion:p.region,addressCountry:p.country}},citation:p.sources.map(s=>s.url)};
 return <><Header/><main id="main"><div className="detail-top wrap"><div className="breadcrumb"><Link href="/#places">The collection</Link> / {p.name}</div><p className="eyebrow">{p.categoryName} · {p.region}, {p.country}</p><h1>{p.name}</h1><p className="detail-intro">{p.hook}</p><SavePlace slug={p.slug} name={p.name}/></div><figure className="wrap"><img src={`/images/${p.slug}.webp`} alt={p.alt} width="1440" height="960" className="detail-photo" fetchPriority="high"/><figcaption className="photo-caption">{p.imageKind==='illustration'?'Illustration':'Photograph'}: {p.credit} · {p.photoDate}{p.imageKind==='photo'?` · ${p.license}`:''}</figcaption></figure><div className="detail-body wrap"><article><section className="story-opening"><p className="eyebrow">In short</p><h2>{p.storyTitle}</h2><p>{p.longStory?.opening??p.story}</p></section>{p.longStory?<FullStory story={p.longStory} sources={p.sources}/>:<section><h2>What’s here today?</h2><p>{p.today}</p></section>}<section className="visit-notes"><p className="eyebrow">Plan a visit</p><h2>Can you visit or stay?</h2><p>{p.access}</p></section><section><h2>Sources behind this entry</h2><ol className="sources-list">{p.sources.map(s=><li id={`source-${p.sources.indexOf(s)+1}`} key={s.url}><a href={s.url}>{s.title}</a></li>)}</ol><p className="source-context">History, local traditions and operator information are identified in the story. Access and booking details can change; check the original source before travelling.</p></section><div className="credit-box">{p.imageKind==='photo'?<><p>Photo by {p.credit}. <a className="text-link" href={p.photoUrl}>Original photograph</a> · <a className="text-link" href={p.licenseUrl}>{p.license}</a>.</p><p>Image resized and compressed; display crops vary by screen.{p.license.includes('BY-SA')?` Image adaptations remain under ${p.license}.`:''}</p></>:<><p>{p.imageNote}</p><a className="text-link" href={p.sources[0].url}>See actual images on the operator’s website</a></>}</div></article><aside><h2>Before you go</h2><span className={`stay-tag ${p.stay?'stay':''}`}>{p.stay?'You can live here':'Visit only'}</span><p>{p.stay?'A temporary hotel stay, subject to booking availability.':'Visitor access; this listing does not offer overnight accommodation.'}</p><p>Sources reviewed<br/><strong>8 October 2026</strong></p><a href={p.sources[0].url} className="text-link">Check visitor information</a></aside></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,'\\u003c')}}/></main><Footer/></>;
}
