export const categories = [{ id:'all',label:'All places' },{ id:'ghost',label:'Ghost towns & forgotten cities' },{ id:'mystery',label:'Mystery & haunted places' },{ id:'stays',label:'Extraordinary stays' }];
export const places = [
 { slug:'kolmanskop',name:'Kolmanskop',region:'Near Lüderitz',country:'Namibia',category:'ghost',categoryName:'Ghost towns & forgotten cities',stay:false,
 hook:'A former diamond town, with sand drifting through its empty rooms.', alt:'Sand-covered floors and peeling walls inside a house in Kolmanskop',storyTitle:'When the desert comes indoors',
 story:'Kolmanskop is a former diamond settlement near Lüderitz. Empty buildings now frame a landscape of drifting sand. The former town is managed as a visitor attraction by Ghost Town Tours.',
 today:'A managed ghost-town attraction. Guided tours provide context for the buildings and their history.',
 access:'Visit through the operator’s permitted access arrangements. Check current tour times and permit conditions before travelling. Accommodation is in the surrounding region, rather than inside the ruins.',legend:'',
 sources:[{title:'Ghost Town Tours — visitor information',url:'https://kolmanskuppe.com/tours-prices/'},{title:'Namibia Tourism Board — Ghost Town Tours',url:'https://visitnamibia.com.na/directory/ghost_town_tours2038/'}],credit:'Damien du Toit',license:'CC BY 2.0',licenseUrl:'https://creativecommons.org/licenses/by/2.0/',photoUrl:'https://commons.wikimedia.org/wiki/File:Kolmanskop_sand.jpg',photoDate:'2006' },
 { slug:'bodie',name:'Bodie',region:'California',country:'United States',category:'ghost',categoryName:'Ghost towns & forgotten cities',stay:false,
 hook:'A gold-rush town preserved with its weathered buildings and belongings.',alt:'An archival 1972 photograph of wooden and brick buildings in Bodie',storyTitle:'A town kept in the middle of leaving',
 story:'Bodie grew around gold mining before its fortunes declined. Mining ended in 1942. Since becoming a state historic park in 1962, its surviving buildings and interiors have been protected in their weathered condition.',
 today:'A California state historic park. Park staff and their families still live and work here; “ghost town” does not mean nobody remains.',
 access:'This is a visitor destination, not public accommodation. Consult California State Parks for hours, road conditions, and tours. Bring supplies: there are no commercial food or fuel facilities in town.',legend:'',
 sources:[{title:'California State Parks — Bodie',url:'https://parks.ca.gov/?page_id=509'},{title:'California State Parks — commonly asked questions',url:'https://www.parks.ca.gov/?page_id=31549'}],credit:'Dick Rowan / EPA / National Archives',license:'Public domain',licenseUrl:'https://commons.wikimedia.org/wiki/File:Ghost_Town_-_NARA_-_543342.jpg#Licensing',photoUrl:'https://commons.wikimedia.org/wiki/File:Ghost_Town_-_NARA_-_543342.jpg',photoDate:'1972' },
 { slug:'bhangarh',name:'Bhangarh Fort',region:'Rajasthan',country:'India',category:'mystery',categoryName:'Mystery & haunted places',stay:false,
 hook:'Ruined passageways and a reputation built around stories of a curse.',alt:'A sequence of stone arches inside Bhangarh Fort',storyTitle:'Stone walls, and the stories around them',
 story:'Bhangarh is a ruined fort in Rajasthan, set among hills. Its surviving architecture is one part of the attraction; its association with haunting stories is another.',
 today:'An archaeological destination associated with local folklore. The ruins are real; supernatural claims are not established facts.',
 access:'Visit only. Rajasthan Tourism states that entry is restricted before sunrise and after sunset. Check current arrangements before travelling; this is not an overnight stay.',
 legend:'Rajasthan Tourism recounts stories of a curse, including a wizard and a princess. These are local legends, not verified explanations for the site’s decline.',
 sources:[{title:'Rajasthan Tourism — Bhangarh Fort',url:'https://www.tourism.rajasthan.gov.in/bhangarh-fort.html'}],credit:'KalkiRaj',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',photoUrl:'https://commons.wikimedia.org/wiki/File:A_view_of_the_gallery_of_the_haunted_fort_of_Bhangarh.jpg',photoDate:'2016' },
 { slug:'mirrorcube',name:'The Mirrorcube',region:'Harads',country:'Sweden',category:'stays',categoryName:'Extraordinary stays',stay:true,
 hook:'A mirrored hotel room that reflects the forest around it.',alt:'The Mirrorcube at Treehotel among snow-covered trees in Harads',storyTitle:'A room that almost disappears',
 story:'At Treehotel in Harads, the Mirrorcube uses reflective exterior walls to blend into the surrounding trees. Inside is a small guest room for one or two people, with a double bed and a balcony.',
 today:'An operating hotel room, rather than a permanent residence. “You can live here” means a bookable temporary stay for this entry.',
 access:'Book through Treehotel. The operator lists a toilet in the room and shower access in a nearby building. Confirm availability, current facilities, and accessibility directly before booking.',legend:'',
 sources:[{title:'Treehotel — official accommodation information',url:'https://agents.treehotel.se/'},{title:'Treehotel — official website',url:'https://treehotel.se/'}],credit:'steffen l',license:'CC BY 2.0',licenseUrl:'https://creativecommons.org/licenses/by/2.0/',photoUrl:'https://commons.wikimedia.org/wiki/File:The_Mirrorcube,_Treehotel_in_Harads,_Sweden_1_-_Jan_3,_2019.jpg',photoDate:'2019' },
];
export type Place = typeof places[number];
