// Image provenance is joined from the verified local manifest in places.ts.
const collectionAdditions = [
 {slug:'hashima',name:'Hashima',region:'Nagasaki',country:'Japan',category:'ghost',stay:false,
 hook:'A coal-mining island left behind, with the silhouette of a battleship.',alt:'Abandoned concrete buildings on Hashima island',storyTitle:'An island built around coal',
 story:'Off the coast of Nagasaki, Hashima is a small island with an outsized industrial history. Coal mining supported a densely built community of apartment blocks and working infrastructure. When mining ended, the community left; the concrete buildings remained. Its outline earned it the name Gunkanjima, or “Battleship Island”.',
 today:'Parts of the island are open through organised tours. The surviving buildings are fragile, so visiting does not mean wandering freely through the apartments. Its industrial story also requires context about the people who worked here, including the history of forced labour during Japan’s wartime period.',
 access:'Visit only, on an authorised group tour from Nagasaki. Landings depend on sea and weather conditions, and visitors follow a restricted route. Check the operator’s conditions before booking.',legend:'',
 sources:[{title:'Japan National Tourism Organization — Hashima',url:'https://www.japan.travel/en/spot/752/'},{title:'UNESCO — Sites of Japan’s Meiji Industrial Revolution',url:'https://whc.unesco.org/en/list/1484/'},{title:'UNESCO / ICOMOS — full-history interpretation mission, 2021',url:'https://whc.unesco.org/document/188249'}]},
 {slug:'dhanushkodi',name:'Dhanushkodi',region:'Near Rameswaram, Tamil Nadu',country:'India',category:'ghost',stay:false,
 hook:'The ruins of a coastal town, shaped by a cyclone and two seas.',alt:'The ruined church at Dhanushkodi',storyTitle:'What the storm left behind',
 story:'At the far end of Rameswaram island, Dhanushkodi’s ruined church and other remains tell the story of a coastal settlement devastated by the 1964 cyclone. The district government records the destruction. The setting is striking, but the ruins are also traces of a disaster that changed people’s lives.',
 today:'Dhanushkodi is a visitor destination at the tip of the island. The “ghost town” description refers to the old settlement’s ruins; it should not erase the people who live or work in the surrounding area.',
 access:'Visit the ruins and coastal area within current local access arrangements. Check road, weather and visiting restrictions locally. This entry does not offer accommodation in the ruined settlement; use Rameswaram as a planning base.',legend:'',
 sources:[{title:'Ramanathapuram District — Dhanushkodi',url:'https://ramanathapuram.nic.in/tourist-place/dhanushkodi/'}]},
 {slug:'kayakoy',name:'Kayaköy',region:'Near Fethiye, Muğla',country:'Türkiye',category:'ghost',stay:false,
 hook:'Roofless hillside homes, carrying a history of displacement.',alt:'Roofless stone houses on the hillside at Kayaköy',storyTitle:'The houses remain. The community changed.',
 story:'South of Fethiye, the old settlement of Kayaköy spreads across a hillside in stone houses, chapels and churches. Türkiye’s Culture Ministry connects its abandonment to the population exchange in the early years of the republic. The missing roofs and empty rooms are the visible part of a much larger story of people leaving their homes.',
 today:'The old settlement is an archaeological visitor site. Distinguish these historic ruins from the surrounding modern village: the name Kayaköy does not mean the whole area is deserted.',
 access:'Visit only within the archaeological site’s current arrangements. Confirm opening hours and admission locally. Nearby accommodation does not mean visitors can stay inside the ruined houses.',legend:'',
 sources:[{title:'Türkiye Culture Ministry — Kayaköy archaeological site',url:'https://www.kulturportali.gov.tr/turkiye/mugla/gezilecekyer/kayakoy'}]},
 {slug:'kuldhara',name:'Kuldhara',region:'Near Jaisalmer, Rajasthan',country:'India',category:'ghost',stay:false,
 hook:'An abandoned desert village, with a departure wrapped in legend.',alt:'Sandstone ruins in the abandoned village of Kuldhara',storyTitle:'A village, and an unanswered departure',
 story:'Near Jaisalmer, Kuldhara’s sandstone ruins preserve the outline of a former village. Rajasthan Tourism describes the site and recounts a dramatic story about its residents leaving. That story is part of the place’s reputation, but a visitor-facing legend should not be treated as a settled historical explanation.',
 today:'A tourist destination where the remains of homes and village structures invite exploration. Its attraction lies in both the surviving settlement and the questions surrounding its abandonment.',
 access:'Visit only. Check current admission, opening hours and local arrangements before travelling. The ruins are not offered as overnight accommodation.',
 legend:'Rajasthan Tourism recounts a tale involving minister Salim Singh, a threatened marriage and the villagers’ departure. Versions include a curse on future settlement. We present this as folklore, not evidence of supernatural events or a verified account of why everyone left.',
 sources:[{title:'Rajasthan Tourism — Kuldhara',url:'https://www.tourism.rajasthan.gov.in/kuldhara.html'}]},
 {slug:'island-of-the-dolls',name:'Island of the Dolls',region:'Xochimilco, Mexico City',country:'Mexico',category:'mystery',stay:false,
 hook:'Dolls hanging among the trees, deep in Xochimilco’s canals.',alt:'Weathered dolls hanging on the Island of the Dolls in Xochimilco',storyTitle:'A collection that became a legend',
 story:'In the canal landscape of Xochimilco, the Island of the Dolls is known for dolls suspended from trees. Mexico City’s tourism authority describes the display as a place where a local legend draws curious visitors. The unsettling objects are real; the supernatural explanations attached to them belong to storytelling.',
 today:'A distinctive canal destination within Xochimilco’s wider cultural and agricultural landscape. Its appeal is the encounter with the display and the stories told about it, rather than a verified haunting.',
 access:'Visit only by arranging an appropriate boat route. Confirm the exact destination with the operator: a trip described as a doll-island visit should identify which site it reaches. Journey times and access need direct confirmation. No overnight stay is established by this listing.',
 legend:'Stories connect the dolls with spirits and the intentions of the island’s former caretaker. These accounts vary. We do not present a reported death or supernatural activity as a verified fact.',
 sources:[{title:'Mexico City Tourism — Xochimilco and the Island of the Dolls',url:'https://www.mexicocity.cdmx.gob.mx/locations/xochimilco/?lang=en'}]},
 {slug:'paris-catacombs',name:'Paris Catacombs',region:'Paris',country:'France',category:'mystery',stay:false,
 hook:'Beneath the city, an ossuary gives the streets another history.',alt:'Human remains arranged along the official Paris Catacombs visitor route',storyTitle:'The city beneath the city',
 story:'The Paris Catacombs are an underground ossuary. Their power comes from a documented history of the city and the care of human remains, rather than needing a ghost story. Below the streets, the official route moves through a place that asks visitors to encounter death, public health and urban history together.',
 today:'A managed museum site with an official visitor route. The wider underground network is not part of the public attraction. These are human remains, so the experience calls for respect as well as curiosity.',
 access:'Visit only through official museum admission. The operator lists stairs down and back up, and specific health and accessibility conditions. Read those conditions before booking. Do not enter unofficial tunnels.',legend:'',
 sources:[{title:'Paris Catacombs — official visitor information',url:'https://www.catacombes.paris.fr/en/visit'},{title:'Paris Catacombs — conditions before visiting',url:'https://www.catacombes.paris.fr/en/visit/please-read-your-visit'}]},
 {slug:'port-arthur',name:'Port Arthur',region:'Tasmania',country:'Australia',category:'mystery',stay:false,
 hook:'A former penal settlement, explored by lantern light and remembered stories.',alt:'Historic buildings and ruins at Port Arthur in Tasmania',storyTitle:'After the visitors leave',
 story:'Port Arthur’s historic buildings and ruins preserve the setting of a former penal settlement. Its official ghost tour explores another layer of that history after dark, with guides recounting stories of unexplained events. The site says ghost stories have been associated with it since 1870; records of stories do not establish the events as supernatural.',
 today:'A managed historic site with daytime interpretation and a separate lantern-lit ghost tour. Its penal history and the lives affected by it deserve attention alongside its eerie reputation.',
 access:'Visit only. Book the official tour for after-dark access rather than entering independently. The operator describes a walking route with limited access through historic buildings; check mobility conditions, departure times and age suitability directly.',
 legend:'Guides recount reports of unexplained encounters associated with the settlement. These are historical accounts and ghost stories, not independently established evidence that the site is haunted.',
 sources:[{title:'Port Arthur Historic Site — official ghost tour',url:'https://portarthur.org.au/ghost-tour/'}]},
 {slug:'stanley-hotel',name:'The Stanley Hotel',region:'Estes Park, Colorado',country:'United States',category:'mystery',stay:true,
 hook:'A historic mountain hotel with ghost stories and a connection to The Shining.',alt:'The exterior of the Stanley Hotel in Estes Park',storyTitle:'A hotel with stories after dark',
 story:'The Stanley Hotel combines an operating hotel with a reputation for spirited storytelling. Its official tours explore the grounds, the hotel’s history and its connection to Stephen King’s The Shining. That literary association is part of its appeal, alongside the stories told about particular places on the property.',
 today:'A hotel and tour destination. The operator offers history, ghost and Shining-related tours; tour access and hotel accommodation are separate arrangements.',
 access:'A temporary hotel stay is possible through booking, and tours can be arranged separately. Confirm room availability, tour requirements and the areas included directly. The operator states that tours do not enter guest rooms.',
 legend:'The hotel recounts purported hauntings and local stories through its ghost tours. We label these as reported experiences and folklore, rather than accepting promotional claims as proof of paranormal activity.',
 sources:[{title:'The Stanley Hotel — official tours',url:'https://www.stanleyhotel.com/tours/'},{title:'The Stanley Hotel — official website',url:'https://www.stanleyhotel.com/'}]},
 {slug:'skylodge',name:'Skylodge Adventure Suites',region:'Sacred Valley, near Ollantaytambo',country:'Peru',category:'stays',stay:true,
 hook:'A transparent sleeping capsule attached to a Sacred Valley cliff.',alt:'Concept illustration of a transparent sleeping capsule on an Andean cliff',storyTitle:'A night on the rock face',
 story:'Natura Vive’s Skylodge places transparent sleeping capsules on a cliff in Peru’s Sacred Valley. The experience joins a night in a small capsule with an organised mountain adventure. The landscape is the central feature: the room opens visually onto the valley while remaining attached to the rock.',
 today:'A bookable adventure stay operated by Natura Vive. The transparent capsules make the valley part of the experience, from arrival on the rock face to the following morning.',
 access:'Book the specific Skylodge overnight experience through Natura Vive. Routes can involve via ferrata and zip lines; confirm the chosen itinerary, fitness requirements, equipment, age limits and weather arrangements with the operator. This is a temporary adventure stay.',legend:'',
 sources:[{title:'Natura Vive — Skylodge Adventure Suites',url:'https://naturavive.com/web/skylodge-adventure-suites/'},{title:'Natura Vive — booking and itineraries',url:'https://naturavive.com/web/booknow/'}]},
 {slug:'whichaway',name:'Whichaway Camp',region:'Schirmacher Oasis',country:'Antarctica',category:'stays',stay:true,
 hook:'Heated sleeping pods in an ice-free corner of Antarctica.',alt:'Concept illustration of an Antarctic sleeping pod beside exposed rock and ice',storyTitle:'An outpost at the edge of the ice',
 story:'White Desert’s Whichaway Camp sits in one of Antarctica’s rare ice-free landscapes, where exposed rock and freshwater lakes meet glacial ice. Its sleeping pods create a small base in an environment that feels far removed from an ordinary hotel stay.',
 today:'A seasonal expedition camp operated by White Desert. Heated pods provide an overnight base for organised Antarctic journeys.',
 access:'Arrange a temporary stay through White Desert’s expedition itineraries. Confirm operating season, flights, medical and insurance requirements, itinerary inclusions and weather contingencies directly. Access requires substantially more planning than a standard hotel booking.',legend:'',
 sources:[{title:'White Desert — Whichaway Camp',url:'https://white-desert.com/camps/whichaway-camp'},{title:'White Desert — Whichaway location fact sheet',url:'https://white-desert.com/wp-content/uploads/2023/07/Whichaway-flyer-2023.pdf'},{title:'White Desert — expedition operator',url:'https://white-desert.com/'}]},
 {slug:'deep-sleep',name:'Deep Sleep',region:'Near Blaenau Ffestiniog, Wales',country:'United Kingdom',category:'stays',stay:true,
 hook:'An underground night reached through a former slate mine.',alt:'Illustration of an underground sleeping cabin in a slate cavern',storyTitle:'Leave daylight at the entrance',
 story:'Go Below’s Deep Sleep is an overnight adventure camp reached through the workings of a former slate mine. The operator places it 1,375 vertical feet below the mountains of Eryri, also known as Snowdonia. The journey underground is part of the stay, with a guide leading the descent and remaining at the camp overnight.',
 today:'A guided underground experience with sleeping cabins and a grotto. Guests reach the camp on a journey through the mine, accompanied by an instructor who remains overnight.',
 access:'Book directly with Go Below. The descent includes steep sections, stairways and scrambles. Confirm age, fitness, equipment and medical suitability with the operator. The overnight trip returns to the surface the following morning.',legend:'',
 sources:[{title:'Go Below — Deep Sleep overnight experience',url:'https://www.go-below.co.uk/deep-sleep.asp'}]},
 {slug:'palacio-de-sal',name:'Palacio de Sal',region:'Near Uyuni',country:'Bolivia',category:'stays',stay:true,
 hook:'A salt-built stay beside the vast white landscape of Salar de Uyuni.',alt:'Concept illustration of a salt-block bedroom with a view of salt flats',storyTitle:'A night shaped by salt',
 story:'On the edge of Salar de Uyuni, Palacio de Sal makes salt part of the architecture as well as the surrounding landscape. The contrast is its draw: an inhabited interior beside a vast salt flat that can appear almost without scale.',
 today:'An operating hotel near the salt flats, with salt-built interiors that connect the overnight experience to the surrounding landscape.',
 access:'Book a temporary stay directly with Palacio de Sal. Confirm transport, the room included, current facilities and conditions for visiting the salt flats. Treat hotel availability and a salt-flat excursion as separate details to verify.',legend:'',
 sources:[{title:'Palacio de Sal — official hotel information',url:'https://palaciodesal.com.bo/en/'}]},
];

import imageProvenance from './image-provenance.json';

export const categories = [{ id:'all',label:'All places' },{ id:'ghost',label:'Ghost towns & forgotten cities' },{ id:'mystery',label:'Mystery & haunted places' },{ id:'stays',label:'Extraordinary stays' }];
const foundationPlaces = [
 { slug:'kolmanskop',name:'Kolmanskop',region:'Near Lüderitz',country:'Namibia',category:'ghost',categoryName:'Ghost towns & forgotten cities',stay:false,
 hook:'A former diamond town, with sand drifting through its empty rooms.', alt:'Sand-covered floors and peeling walls inside a house in Kolmanskop',storyTitle:'When the desert comes indoors',
 story:'Kolmanskop is a former diamond settlement near Lüderitz. Empty buildings now frame a landscape of drifting sand. The former town is managed as a visitor attraction by Ghost Town Tours.',
 today:'A managed ghost-town attraction. Guided tours provide context for the buildings and their history.',
 access:'Visit through the operator’s permitted access arrangements. Check current tour times and permit conditions before travelling. Accommodation is in the surrounding region, rather than inside the ruins.',legend:'',
 sources:[{title:'Ghost Town Tours — visitor information',url:'https://kolmanskuppe.com/tours-prices/'},{title:'Namibia Tourism Board — Ghost Town Tours',url:'https://visitnamibia.com.na/directory/ghost_town_tours2038/'}],credit:'Damien du Toit',license:'CC BY 2.0',licenseUrl:'https://creativecommons.org/licenses/by/2.0/',photoUrl:'https://commons.wikimedia.org/wiki/File:Kolmanskop_sand.jpg',photoDate:'2006' },
 { slug:'bodie',name:'Bodie',region:'California',country:'United States',category:'ghost',categoryName:'Ghost towns & forgotten cities',stay:false,
 hook:'A gold-rush town preserved with its weathered buildings and belongings.',alt:'An archival 1972 photograph of wooden and brick buildings in Bodie',storyTitle:'A town kept in the middle of leaving',
 story:'Bodie grew around gold mining before its fortunes declined. Mining ended in 1942. Since becoming a state historic park in 1962, its surviving buildings and interiors have been protected in their weathered condition.',
 today:'A California state historic park. Park staff and their families still live and work here; “ghost town” does not mean nobody remains.',
 access:'This is a visitor destination, not public accommodation. Consult California State Parks for hours, road conditions, and tours. Bring supplies: there are no commercial food or fuel facilities in town.',legend:'',
 sources:[{title:'California State Parks — Bodie',url:'https://parks.ca.gov/?page_id=509'},{title:'California State Parks — commonly asked questions',url:'https://www.parks.ca.gov/?page_id=31549'}],credit:'Dick Rowan / EPA / National Archives',license:'Public domain',licenseUrl:'https://commons.wikimedia.org/wiki/File:Ghost_Town_-_NARA_-_543342.jpg#Licensing',photoUrl:'https://commons.wikimedia.org/wiki/File:Ghost_Town_-_NARA_-_543342.jpg',photoDate:'1972' },
 { slug:'bhangarh',name:'Bhangarh Fort',region:'Rajasthan',country:'India',category:'mystery',categoryName:'Mystery & haunted places',stay:false,
 hook:'Ruined passageways and a reputation built around stories of a curse.',alt:'A sequence of stone arches inside Bhangarh Fort',storyTitle:'Stone walls, and the stories around them',
 story:'Bhangarh is a ruined fort in Rajasthan, set among hills. Its surviving architecture is one part of the attraction; its association with haunting stories is another.',
 today:'An archaeological destination associated with local folklore. The ruins are real; supernatural claims are not established facts.',
 access:'Visit only. Rajasthan Tourism states that entry is restricted before sunrise and after sunset. Check current arrangements before travelling; this is not an overnight stay.',
 legend:'Rajasthan Tourism recounts stories of a curse, including a wizard and a princess. These are local legends, not verified explanations for the site’s decline.',
 sources:[{title:'Rajasthan Tourism — Bhangarh Fort',url:'https://www.tourism.rajasthan.gov.in/bhangarh-fort.html'}],credit:'KalkiRaj',license:'CC BY-SA 4.0',licenseUrl:'https://creativecommons.org/licenses/by-sa/4.0/',photoUrl:'https://commons.wikimedia.org/wiki/File:A_view_of_the_gallery_of_the_haunted_fort_of_Bhangarh.jpg',photoDate:'2016' },
 { slug:'mirrorcube',name:'The Mirrorcube',region:'Harads',country:'Sweden',category:'stays',categoryName:'Extraordinary stays',stay:true,
 hook:'A mirrored hotel room that reflects the forest around it.',alt:'The Mirrorcube at Treehotel among snow-covered trees in Harads',storyTitle:'A room that almost disappears',
 story:'At Treehotel in Harads, the Mirrorcube uses reflective exterior walls to blend into the surrounding trees. Inside is a small guest room for one or two people, with a double bed and a balcony.',
 today:'An operating hotel room, rather than a permanent residence. “You can live here” means a bookable temporary stay for this entry.',
 access:'Book through Treehotel. The operator lists a toilet in the room and shower access in a nearby building. Confirm availability, current facilities, and accessibility directly before booking.',legend:'',
 sources:[{title:'Treehotel — official accommodation information',url:'https://treehotel.se/treerooms/mirrorcube/'},{title:'Treehotel — official website',url:'https://treehotel.se/'}],credit:'steffen l',license:'CC BY 2.0',licenseUrl:'https://creativecommons.org/licenses/by/2.0/',photoUrl:'https://commons.wikimedia.org/wiki/File:The_Mirrorcube,_Treehotel_in_Harads,_Sweden_1_-_Jan_3,_2019.jpg',photoDate:'2019' },
];
export type StoryChapter = {title:string; text:string; references:string[]; kind?:'folklore'|'context'};
export type LongStory = {opening:string; chapters:StoryChapter[]};
// Original editorial writing. Chapter references point to the sources read for each claim.
const storySources:Record<string,{title:string;url:string}> = {
 jnto:{title:'Japan National Tourism Organization — Hashima',url:'https://www.japan.travel/en/spot/752/'},
 hashimaHeritage:{title:'UNESCO — Japan’s Meiji industrial heritage',url:'https://whc.unesco.org/en/list/1484/'},
 hashimaHistory:{title:'UNESCO / ICOMOS — full-history interpretation mission, 2021',url:'https://whc.unesco.org/document/188249'},
 dhanushkodi:{title:'Ramanathapuram District — Dhanushkodi',url:'https://ramanathapuram.nic.in/tourist-place/dhanushkodi/'},
 lighthouse:{title:'Government of India — Dhanushkodi Lighthouse',url:'https://dgll.nic.in/DGLL-light-house-location/about-chennai/dhanushkodi-lighthouse'},
 kayakoy:{title:'Türkiye Culture Ministry — Kayaköy archaeological site',url:'https://www.kulturportali.gov.tr/turkiye/mugla/gezilecekyer/kayakoy'},
 kuldhara:{title:'Rajasthan Tourism — Kuldhara and its local legend',url:'https://www.tourism.rajasthan.gov.in/kuldhara.html'},
 kuldharaStudy:{title:'Roy et al. — deserted Paliwal villages and palaeoseismicity, Current Science (2017)',url:'https://www.researchgate.net/publication/312385113_Deserted_Nineteenth_Century_Paliwal_Villages_around_Jaisalmer_Western_Rajasthan_IndiaHistorical_Evidence_of_Palaeoseismicity'},
 kuldharaDebate:{title:'Bahadur, Pandya & Singh — Kuldhara devastation and the great exodus; response by Roy et al., Current Science (2018)',url:'https://www.researchgate.net/publication/323797999_Kuldhara_Devastation_and_the_Great_Exodus'},
 kolmanskop:{title:'Ghost Town Tours — Kolmanskop’s diamond-rush origins',url:'https://kolmanskuppe.com/'},
 kolmanskopReport:{title:'Paul Cooper / National Geographic — Kolmanskop’s colonial history (2019)',url:'https://www.nationalgeographic.com/travel/article/eerie-fascinating-pictures-kolmanskop-desert-diamond-ghost-town'},
 dolls:{title:'Mexico City Tourism — Xochimilco and the Island of the Dolls',url:'https://www.mexicocity.cdmx.gob.mx/locations/xochimilco/?lang=en'},
 xochimilco:{title:'UNESCO — Historic Centre of Mexico City and Xochimilco',url:'https://whc.unesco.org/en/list/412/'},
 bhangarh:{title:'Rajasthan Tourism — Bhangarh Fort and its legends',url:'https://www.tourism.rajasthan.gov.in/bhangarh-fort.html'},
 bhangarhSurvey:{title:'ASI monument record, hosted by IGNCA — Ancient Site, Bhangarh',url:'https://ignca.gov.in/Asi_data/88329.pdf'},
 catacombsHistory:{title:'Paris Catacombs — site history',url:'https://www.catacombes.paris.fr/en/history/site-history'},
 catacombsOssuary:{title:'Paris Catacombs — the ossuary and its arrangement',url:'https://www.catacombes.paris.fr/en/history/ossuary'},
 portHistory:{title:'Port Arthur Historic Site — history',url:'https://portarthur.org.au/history/'},
 portGhosts:{title:'Port Arthur Historic Site — ghost tour',url:'https://portarthur.org.au/ghost-tour/'},
 stanleyKing:{title:'Stephen King — The Shining: the author’s account of its inspiration',url:'https://stephenking.com/works/novel/shining.html'},
 stanleyTours:{title:'The Stanley Hotel — history, ghost and Shining tours',url:'https://www.stanleyhotel.com/tours/'},
 skylodge:{title:'Natura Vive — Skylodge’s origins and overnight experience',url:'https://naturavive.com/web/skylodge-adventure-suites/'},
 skylodgePeru:{title:'Peru’s official tourism portal — Skylodge in the Sacred Valley (2024)',url:'https://www.peru.travel/stories/pure-adrenaline-visit-the-only-suspended-hotel-in-the-mountains-of-the-sacred-valley'},
 mirrorcubeArchitect:{title:'Tham & Videgård — Tree Hotel / Mirrorcube project',url:'https://thamvidegard.se/work/tree-hotel'},
 mirrorcube:{title:'Treehotel — The Mirrorcube',url:'https://treehotel.se/treerooms/mirrorcube/'},
 whichaway:{title:'White Desert — Whichaway Camp',url:'https://white-desert.com/camps/whichaway-camp'},
 whichawaySheet:{title:'White Desert — Whichaway location fact sheet (2023)',url:'https://white-desert.com/wp-content/uploads/2023/07/Whichaway-flyer-2023.pdf'},
 deepSleep:{title:'Go Below — Deep Sleep overnight adventure and FAQ',url:'https://www.go-below.co.uk/deep-sleep.asp'},
 slateHistory:{title:'UNESCO — The Slate Landscape of Northwest Wales',url:'https://whc.unesco.org/en/list/1633'},
 saltHistory:{title:'Palacio de Sal — the founder and the hotel’s move',url:'https://palaciodesal.com.bo/en/first-salt-hotel/'},
 saltHotel:{title:'Palacio de Sal — official hotel information',url:'https://palaciodesal.com.bo/en/'}
};
const longStories:Record<string,LongStory> = {
 hashima:{opening:'From the water, Hashima looks like a ship that never sailed. The concrete silhouette is only the beginning: inside it was a community built around coal, and a history that deserves more than a photograph of empty windows.',chapters:[
  {title:'A whole world on a small island',text:'Hashima’s nickname, Gunkanjima, comes from its battleship-like outline. But this was a working settlement, not a fortress. Mitsubishi developed its coal industry, and the island supported shops, a hospital, two schools and places of worship. Families lived beside the industry that kept them there. The empty buildings make more sense when you remember how many ordinary routines once fitted into this small space.',references:['jnto']},
  {title:'When the coal stopped',text:'As Japan’s energy needs changed, the mines closed around 1974 and the community departed. Buildings that had supported everyday life were left exposed to the sea and weather. Tourism returned in 2009; Hashima later became part of the Meiji industrial heritage property inscribed by UNESCO in 2015. The island’s new role is to help people understand the industrial world that produced it.',references:['jnto','hashimaHeritage']},
  {title:'The history beyond the skyline',kind:'context',text:'Industrial achievement is only part of the account. The UNESCO / ICOMOS mission report from 2021 examined how wartime forced labour was being interpreted, including Koreans and others brought against their will. It found the measures for explaining that history insufficient. Reading Hashima means making room for those experiences too. An abandoned building can be visually striking while carrying a history of suffering that its silhouette cannot explain.',references:['hashimaHistory']}
 ]},
 dhanushkodi:{opening:'At Dhanushkodi, a ruined church stands near the end of an island. The coast makes a striking picture, but the story begins with a settlement that was lost—and continues with people whose work still depends on these waters.',chapters:[
  {title:'A town at the island’s edge',text:'Dhanushkodi lies at the southern tip of Rameswaram island. The district administration records the cyclone that devastated it in 1964. The ruined church is one visible reminder; the remains of the old railway station are another. These were parts of an inhabited place. Looking at them as traces of everyday life gives the landscape a weight that the phrase “ghost town” alone cannot carry.',references:['dhanushkodi','lighthouse']},
  {title:'What survived the storm',text:'The district’s account notes that the Kothandaramasamy Temple remained intact. It also records the local religious belief connecting the place to Vibhishana and Rama. That tradition belongs to the site’s spiritual significance; the cyclone belongs to its documented modern history. Both influence how people encounter Dhanushkodi, but they answer different questions about the place.',references:['dhanushkodi']},
  {title:'A coast that still has a purpose',text:'The lighthouse authority provides a useful counterpoint to the idea of a completely lifeless town. A new lighthouse was commissioned in May 2022 near the ruined station and church, between the Palk Strait and Gulf of Mannar. Its role includes helping local fishing boats navigate safely. The old settlement’s destruction did not bring the surrounding coast’s life to an end. Here, a ruin and a working navigation light tell two parts of the same continuing story.',references:['lighthouse']}
 ]},
 kayakoy:{opening:'Kayaköy’s houses climb a hillside without their roofs. Their arrangement still suggests neighbours, shared daylight and familiar routes. Understanding why those rooms are empty means looking beyond the picturesque ruin to the people who had to leave.',chapters:[
  {title:'Homes designed around one another',text:'The Culture Ministry attributes the surviving hillside buildings to the late Ottoman Greek community. It describes two-storey homes arranged to preserve one another’s light and views, with storage below and cisterns collecting rainwater. Chapels, two large churches and a school formed part of the settlement. The houses were designed for a community, even if today the eye first notices their empty shells.',references:['kayakoy']},
  {title:'A departure tied to population exchange',text:'The ministry connects the settlement’s evacuation to the population exchange in the early years of the Turkish republic. That makes displacement central to its story. Its ghost-town appearance developed as wooden doors, windows and roofs deteriorated after the residents left. The missing roofs are a later visible consequence of that break in the community’s life.',references:['kayakoy']},
  {title:'Reading the empty rooms',text:'Kayaköy rewards a slower kind of attention. The ministry’s description directs us to homes, rainwater systems and places of worship: the evidence of how residents made a life here. Look from one house to the next and the arrangement begins to suggest the life of a neighbourhood. The empty hillside carries a story of people making homes, and then losing their place within them.',references:['kayakoy']}
 ]},
 kuldhara:{opening:'Kuldhara invites a question almost as soon as you see its empty lanes: why did the people leave? A curse supplies the famous answer. The research supplies something more interesting—a disagreement about how to read the ruins.',chapters:[
  {title:'The village behind the reputation',text:'Rajasthan Tourism identifies Kuldhara with the Paliwal community and describes a protected settlement of ruined houses and narrow lanes near Jaisalmer. Before the ghost stories, this was a place of homes and agricultural work. Its surviving plan is a reminder that abandonment happened to a community, not simply to a collection of photogenic stone walls.',references:['kuldhara']},
  {title:'The departure people retell',kind:'folklore',text:'The tourism authority recounts a legend in which minister Salim Singh demands to marry the village head’s daughter. The residents leave rather than submit, cursing future settlement as they go. It is a memorable story of coercion and collective refusal. We present the marriage demand, overnight departure and curse as the legend’s account, not a verified chain of events or evidence of supernatural powers.',references:['kuldhara']},
  {title:'A mystery with competing readings',kind:'context',text:'In a 2017 Current Science paper, Roy and colleagues interpreted collapsed houses and regional geological features as evidence of earthquake-related destruction. A 2018 correspondence by Bahadur, Pandya and Singh challenged that explanation, arguing from historical records for oppression and migration; Roy’s group replied in defence of its geological interpretation. The disagreement matters. Damage to buildings and the departure of residents are related questions, but one does not automatically explain the other. Kuldhara is worth exploring with that uncertainty intact.',references:['kuldharaStudy','kuldharaDebate']}
 ]},
 kolmanskop:{opening:'A doorway at Kolmanskop may open onto a room filled with sand. The desert is easy to notice. Less immediately visible is the mining economy—and the unequal colonial world—that once made a town here possible.',chapters:[
  {title:'A town built on a discovery',text:'The site operator dates the diamond discovery that sparked the rush to 1908. Fortune seekers arrived, and a settlement grew near Lüderitz in the Namib Desert. National Geographic’s account identifies railway worker Zacharias Lewala with that discovery. The town’s surviving rooms belong to this short, intense period of mineral wealth, when the promise of diamonds drew people into an environment that would later outlast the settlement.',references:['kolmanskop','kolmanskopReport']},
  {title:'The wealth had a wider history',kind:'context',text:'National Geographic places Kolmanskop within German colonial rule and describes the exploitation behind the diamond boom. That context changes how the elegant interiors should be read. They are evidence of wealth, but they cannot stand for everyone’s experience of the mining economy. A visit that only admires the architecture leaves out the unequal conditions that helped produce it.',references:['kolmanskopReport']},
  {title:'The desert comes indoors',text:'The operator now presents the surviving settlement through guided visits. Sand moving into former living spaces makes the boundaries between house and landscape feel unstable: a floor becomes a dune, and a window frames another empty room. The result is compelling without a ghost story. Kolmanskop’s appeal lies in seeing a built place change after the activity that sustained it has gone.',references:['kolmanskop']}
 ]},
 'island-of-the-dolls':{opening:'The dolls are what catch your attention first. To understand their setting, though, you have to look past the hanging figures to Xochimilco’s waterways—a living landscape much larger than one unsettling destination.',chapters:[
  {title:'A journey through a working landscape',text:'Xochimilco’s canals are part of an agricultural system whose history reaches far beyond modern sightseeing. UNESCO describes the chinampas as human-made islands in shallow water and recognises the landscape as evidence of traditional land use. They are not merely scenery on the way to an attraction. The waterways belong to a place shaped by cultivation, community and continuing environmental pressures.',references:['xochimilco']},
  {title:'The display and the legend',kind:'folklore',text:'Mexico City’s tourism authority describes hundreds of dolls hanging in trees, with a local legend drawing curious visitors. The display is the tangible part of the encounter. Stories about spirits and the caretaker’s intentions are the interpretive layer around it. The official page is not enough to establish every dramatic origin story repeated online, so we leave disputed deaths and supernatural explanations out of the factual account.',references:['dolls']},
  {title:'More than an eerie photograph',text:'The same tourism authority describes canal journeys in decorated trajineras, passing productive chinampas, birds and greenhouses. That wider setting makes the island more interesting: an unsettling collection encountered within an inhabited cultural landscape. UNESCO also records threats to the chinampa system from development, contamination and groundwater extraction. Curiosity about the dolls can be a beginning, rather than the whole reason to pay attention to Xochimilco.',references:['dolls','xochimilco']}
 ]},
 bhangarh:{opening:'Bhangarh has a reputation that can arrive before you do. Once inside the story, the ruined town matters as much as the curse: temples, market remains and a palace give the imagination something substantial to work with.',chapters:[
  {title:'A town inside the fort',text:'Rajasthan Tourism describes Bhangarh among the Aravalli hills, with a ruined market, havelis and a royal palace. The ASI monument record’s plan also identifies gates, roads and temples across the ancient site. This was a settlement with different kinds of spaces, not simply one ominous building. Its remaining architecture is a useful starting point before the supernatural reputation takes over.',references:['bhangarh','bhangarhSurvey']},
  {title:'Two versions of a curse',kind:'folklore',text:'The tourism authority recounts two prominent legends. One concerns a holy man’s warning that a building’s shadow must not fall on his home. Another tells of Princess Ratnavati, a wizard and a bewitched perfume that she rejects. In both accounts, a curse explains the town’s fate. They are local storytelling traditions; neither is established here as the historical cause of Bhangarh’s decline.',references:['bhangarh']},
  {title:'What the ruins can tell you',text:'An archaeological plan and a legend offer different ways into the same place. The first shows the settlement’s physical layout; the second shows how people have imagined its fate. Keeping both in view lets Bhangarh remain atmospheric without turning a reported curse into a fact. The strongest detail may be a surviving passageway, and the question of who once walked through it.',references:['bhangarhSurvey','bhangarh']}
 ]},
 'paris-catacombs':{opening:'Under Paris, human remains became part of another kind of city architecture. The Catacombs are unsettling because of what they contain, but their origin is a practical story about overcrowded cemeteries and the spaces left beneath the streets.',chapters:[
  {title:'A city makes room for its dead',text:'In the late eighteenth century, public health concerns prompted Paris to move cemetery remains into former quarries. The museum records transfers from the Saints-Innocents cemetery between 1785 and 1787. Bones were transported at night, then moved into the galleries by quarry workers. The underground landscape had already been shaped by extracting stone; it was now being given a new municipal purpose.',references:['catacombsHistory']},
  {title:'The arrangement was deliberate',text:'The ordered walls visitors see did not begin as an ordered display. According to the museum, Héricart de Thury oversaw a rearrangement before public opening in 1809. Long bones and skulls formed the visible walls, with other remains placed behind them. Monuments and inscriptions added a route for reflection. The experience was designed to be more than a store of bones: it was also a way of thinking about death.',references:['catacombsOssuary']},
  {title:'Looking with care',text:'The museum’s account describes poetic and religious plaques encouraging introspection. They offer a useful cue for today’s visitor. These remains were once people, and the site’s visual power comes with that responsibility. Its history is already extraordinary: a city moved its dead, reorganised the underground space and opened it to the living. A supernatural explanation adds little to what is actually here.',references:['catacombsOssuary','catacombsHistory']}
 ]},
 'port-arthur':{opening:'Port Arthur can be encountered in daylight as a historic landscape, or after dark as a place of lanterns and reported encounters. Its most important story survives in both: the lives of people caught within a penal settlement.',chapters:[
  {title:'Before the ghost tour',text:'The site’s official history begins with a small timber station in 1830. It developed into a penal settlement, with shipbuilding among the activities intended to give selected convicts a skill for life after release. The buildings and ruins therefore record systems of punishment as well as work. Paying attention to those uses makes the place more legible than treating every empty doorway as a supernatural invitation.',references:['portHistory']},
  {title:'A place that changed after punishment',text:'Port Arthur did not become a static ruin when the last convict left. The official history describes its renaming as Carnarvon, land auctions and people taking up residence around the old site in the 1880s. Today’s heritage destination is the result of later lives and uses as well as the penal years. Its history includes people choosing to settle where others had once been confined.',references:['portHistory']},
  {title:'Stories by lantern light',kind:'folklore',text:'The operator’s ghost tour follows a separate after-dark route, sharing accounts of unexplained encounters. It says ghost stories have circulated here since 1870. That dates a tradition of reporting stories; it does not establish paranormal events. The tour can be an atmospheric way to encounter the buildings while the daytime history remains essential to understanding the people behind them.',references:['portGhosts']}
 ]},
 'stanley-hotel':{opening:'The Stanley’s most famous visitor left with the beginnings of a novel. A stay here can bring you close to the setting that stirred his imagination, while the hotel’s own history and reported ghost stories remain separate threads.',chapters:[
  {title:'The night that became an idea',text:'On his official website, Stephen King recalls staying at the Stanley with Tabitha in late September 1974. He describes an almost empty hotel about to close for winter, wandering its corridors and dreaming of his young son being chased by a fire hose. By the end of that night, he says, the structure of The Shining had taken shape in his mind. It is an author’s account of inspiration, not evidence of a haunting.',references:['stanleyKing']},
  {title:'An inspiration, not the screen’s hotel',text:'The Stanley’s official Shining tour distinguishes the novel, Stanley Kubrick’s 1980 film and the 1997 miniseries. It explains that Kubrick’s film was not shot at the Stanley, while King’s miniseries was. That distinction is worth holding onto: a real location can inspire a fictional one without appearing in every adaptation. Part of visiting is discovering where the familiar story and the actual building diverge.',references:['stanleyTours']},
  {title:'The stories the hotel tells',kind:'folklore',text:'The operator also runs history and ghost tours. The latter present purported encounters and folklore around the property. They belong to the hotel’s storytelling tradition, rather than a verified record of supernatural activity. You can enjoy the atmosphere, ask questions and keep the boundary clear. The literary connection is documented; a ghost remains a claim.',references:['stanleyTours','stanleyKing']}
 ]},
 skylodge:{opening:'At Skylodge, getting to bed is part of the adventure. A transparent capsule on a Sacred Valley cliff turns the familiar idea of a room with a view into a different question: how close to the landscape would you like to sleep?',chapters:[
  {title:'Putting a bedroom on the rock face',text:'Natura Vive says it opened Skylodge in June 2013. Its transparent capsules attach to a cliff in Peru’s Sacred Valley, making the landscape part of the room rather than something glimpsed beyond a conventional hotel window. The project brings an overnight stay together with the mountain activities the operator already offers. The capsule’s position makes arrival, shelter and the view parts of the same experience.',references:['skylodge']},
  {title:'The arrival is part of the story',text:'Peru’s tourism portal describes access as an adventure in itself, involving a via ferrata or a route using zip lines. The operator’s own information also sets out climbing and hiking options. The route is therefore something to choose and confirm with guides, not an incidental transfer. Before the night above the valley comes the physical experience of reaching the capsule.',references:['skylodgePeru','skylodge']},
  {title:'A small interior, a large view',text:'Once inside, the transparent enclosure keeps the valley visually present. Natura Vive describes bedding, a separate bathroom and privacy curtains: practical details that make an unusual location habitable for a night. The appeal is the contrast between a compact sleeping space and the scale outside it. Whether that contrast feels exciting or uncomfortable is part of deciding if this is your kind of stay.',references:['skylodge']}
 ]},
 mirrorcube:{opening:'The Mirrorcube makes the forest part of its exterior. Sky and trees appear on its reflective walls, while a small room sits inside. The design is an unusually clear expression of wanting to enter nature—and still bring shelter with you.',chapters:[
  {title:'A treehouse built around a paradox',text:'Architects Tham & Videgård describe the starting point as the relationship between people and nature: the desire for an authentic encounter, alongside the advanced materials used to make it possible. On a wooded hillside near Harads, they created a reflective cube around a pine. It belongs to the forest visually while remaining an unmistakably designed object.',references:['mirrorcubeArchitect']},
  {title:'Reflection outside, plywood inside',text:'The architects describe a lightweight aluminium structure, a four-metre cube and reflective glass that catches the surrounding trees and sky. Inside, plywood and windows give the small room a different character. The contrast is the idea: an exterior that appears to borrow its image from the landscape, and an interior built to hold a guest within it. Treehotel dates its construction to 2010.',references:['mirrorcubeArchitect','mirrorcube']},
  {title:'The reality of a night in the trees',text:'Treehotel lists this specific room for two people, with a double bed and a balcony accessed by a step ladder. Shower facilities are in a nearby building. Those details ground the striking exterior in an actual overnight experience. This entry is about one room and its design, so you can decide whether the idea appeals before following the operator’s booking information.',references:['mirrorcube']}
 ]},
 whichaway:{opening:'Antarctica is often imagined as uninterrupted white. Whichaway sits in a different landscape: exposed rock, freshwater lakes and nearby glacial ice. The unusual stay begins with that contrast, before you step into a heated pod.',chapters:[
  {title:'An oasis in the ice',text:'White Desert’s location fact sheet places Whichaway in the Schirmacher Oasis in Queen Maud Land. It describes freshwater lakes and an icefall around the camp. Here, “oasis” means an ice-free landscape, not a warm one. The exposed ground makes a small base possible in an environment where the broader ice landscape still determines the scale of the journey.',references:['whichawaySheet']},
  {title:'A name from finding the way',text:'The operator tells a modest origin story for the name: its founder became a little lost crossing the landscape and wondered which way to go. Its current account dates the camp’s opening to 2005 and says it occupies the site of a former East German science base. That gives the place a history of human presence alongside the feeling of remoteness.',references:['whichaway']},
  {title:'Shelter inside an expedition',text:'The camp’s heated pods and communal spaces provide the overnight base. The 2023 fact sheet describes access by flight from Cape Town, while the current camp page presents Whichaway within White Desert’s Antarctic journeys. This is an expedition arrangement, with travel and weather planning around the stay. Its appeal is the possibility of spending time within that landscape, rather than treating the pod as an ordinary hotel room in an extraordinary postcode.',references:['whichawaySheet','whichaway']}
 ]},
 'deep-sleep':{opening:'Deep Sleep begins above ground. The descent through a former slate mine is what makes the overnight camp unusual: a bed becomes the pause between entering the mountain and returning to daylight the next morning.',chapters:[
  {title:'The landscape was made by work',text:'Northwest Wales’s slate industry transformed mountains, communities and transport routes. UNESCO describes quarries, mines, large underground chambers and the settlements that grew around them. That is the regional industrial context for Deep Sleep, rather than a claim that the camp itself has World Heritage status. The space beneath the mountain exists because people once worked to remove stone from it.',references:['slateHistory']},
  {title:'The route to the sleeping chamber',text:'Go Below describes a mountain walk, then a guided descent through old mine workings using stairs, bridges and scrambles. The operator places the camp 1,375 vertical feet below the mountains. A guide supplies historical context along the way and stays underground overnight. Getting there is a substantial part of the experience, which the operator explicitly describes as a remote-camp adventure rather than a conventional hotel.',references:['deepSleep']},
  {title:'A night without a window to the sky',text:'At the camp, insulated cabins provide shelter inside the chamber. The operator explains that mine conditions can include falling-water sounds, and that low-voltage lighting uses batteries charged by micro-hydro power, with surface backup. Morning brings the ascent back out. The unusual detail is this complete change of setting: the route, the camp and the return all belong to one overnight journey.',references:['deepSleep']}
 ]},
 'palacio-de-sal':{opening:'At Palacio de Sal, the material associated with the landscape also becomes part of the building. A night beside Salar de Uyuni turns salt from something underfoot into something that surrounds an interior.',chapters:[
  {title:'An idea that became a hotel',text:'The hotel credits Juan Quesada Valda with imagining a place built from salt. Its official history places the beginning in the late 1990s and describes his children continuing the project. The idea makes the building’s material the reason to notice it: the setting influences the architecture rather than serving only as a view from a standard room.',references:['saltHistory']},
  {title:'From the salt flat to its edge',text:'The same history records a later move from within Salar de Uyuni to its edge. The operator presents that relocation as a way to keep the landscape central while moving the hotel outside the formation itself. It is a useful distinction when imagining the stay. The current hotel is beside the salt flat; the origin story should not leave readers expecting a room at its centre.',references:['saltHistory']},
  {title:'A place to pause beside the salar',text:'Palacio de Sal now operates as a hotel, with salt-based architecture connecting its interiors to the surrounding landscape. The stay and a journey onto the salar remain separate arrangements to check. Our interest here is the architectural idea and the experience of pausing beside that vast setting. The attraction is that relationship between shelter and place: the material associated with a vast outdoor landscape is brought into the more intimate scale of a building.',references:['saltHotel','saltHistory']}
 ]}
};
export type Place = (typeof foundationPlaces)[number] & {imageKind: string; imageNote: string;longStory?:LongStory};
const names:Record<string,string>={ghost:'Ghost towns & forgotten cities',mystery:'Mystery & haunted places',stays:'Extraordinary stays'};
const provenance = imageProvenance as Record<string,{imageKind:string;imageNote:string;credit:string;license:string;licenseUrl:string;photoUrl:string;photoDate:string}>;
const foundation=foundationPlaces.map(p=>({...p,imageKind:'photo',imageNote:'Photograph resized, compressed, and cropped for display.'}));
const additions:Place[]=collectionAdditions.map(p=>({...p,categoryName:names[p.category],...provenance[p.slug]}));
const all:Place[]=[...foundation,...additions].map(p=>{
 const longStory=longStories[p.slug];
 const sources=[...p.sources];
 for(const id of longStory?.chapters.flatMap(c=>c.references)??[]){const source=storySources[id];if(!source)throw new Error('Missing story source: '+id);if(!sources.some(s=>s.url===source.url))sources.push(source);}
 return {...p,sources,longStory:longStory?{...longStory,chapters:longStory.chapters.map(c=>({...c,references:c.references.map(id=>storySources[id].url)}))}:undefined};
});
const order=['hashima','dhanushkodi','kayakoy','kuldhara','kolmanskop','island-of-the-dolls','bhangarh','paris-catacombs','port-arthur','stanley-hotel','skylodge','mirrorcube','whichaway','deep-sleep','palacio-de-sal'];
export const places:Place[]=order.map(slug=>{const place=all.find(p=>p.slug===slug);if(!place)throw new Error('Missing collection place: '+slug);return place;});
// Preserve the original Bodie story URL without including it in the selected collection.
export const findPlace=(slug:string)=>all.find(p=>p.slug===slug);
